target 'iosApp' do
  use_frameworks!
  platform :ios, '13'
  pod 'composeApp', :path => '../composeApp'
  pod 'sqlite3', '~> 3.42.0'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
  end
 end
end
